### ISSUE TITLE
Make prerelease environment point to pre release's cognito

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-infra#12]
Check with Himesh with there is any issue if we make this change.

**Comment by vinayvenu** [comment]
This will require some engineering around duplicating users from the environment from where the database is taken. Moving to 8.0

**Comment by himeshr** [comment]
Not possible, as we keep refreshing prerelease db with Prod snapshot, resulting in us having to connect to prod cognito in prerelease env.
