### ISSUE TITLE
load is high on Read DB used by Superset reports

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-infra#13]
Freshdesk ticket: https://avni.freshdesk.com/a/tickets/3050

### How to reproduce:
- Open multiple APF reports simultaneously
- You will face the issues as attached in the screenshot

![Image](https://user-images.githubusercontent.com/10369963/267574965-912f0d71-e44a-49ed-90f1-8dfc88c766ea.png)

![Image](https://user-images.githubusercontent.com/10369963/267575143-edd2e3f1-0ef7-4a35-9c8b-45b4a063fbe4.png)

### Analysis:
- superset-db DB load Monitoring graph shows that it has frequently reached the maximum limit
- So, might need to upgrade from micro to small

### Why high priority:
APF users use reports on a day-to-day basis and hence affecting their daily work.

**Comment by 1t5j0y** [comment]
There is insignificant load on the Superset DB.

The load is on the prod read db:
- connection count is continuously close to the limit
- read IO increases significantly (probably due to memory pressure) when multiple reports are run together

Superset is configured to timeout after 60 seconds. Increasing this timeout should result in the report loading but slowly without changing current server specs.
The other option is to bump up prod read db instance class.

FYI @vinayvenu to determine which course of action to take.

**Comment by mahalakshme** [comment]
Yeah I interpreted the metrics incorrectly bigtime :P looks like the no of db connections to readdb at a time is frequently more(exceeded 120) than prod db. so increasing the db size to medium(in par with prod db) from small will help considering higher memory, though micro itself will support until 170 connections.(https://sysadminxpert.com/aws-rds-max-connections-limit/).
I think incresing timeout might not be good considering the reports are already slow. 
@vinayvenu

**Comment by vinayvenu** [comment]
@1t5j0y @mahalakshme we have moved out most reports into etl, this should have reduced load on db except for maybe some bad ones. Worth looking at them once to see if a few bad reports are causing trouble?

**Comment by vinayvenu** [comment]
Also, superset and avni have a 60 second limit, but db queries don't. We could limit to 2 minutes and see if it reduces load from useless queries

**Comment by 1t5j0y** [comment]
Do Jasper and Metabase also have a 60 second limit?

Additional context around report performance - The report in the screenshots above returned in under 40 seconds when executed. The issue only occurred when multiple instances of this report were triggered at the same time.

**Comment by mahalakshme** [comment]
yeah agreed, when loading just one report, the report was able to load. anyways the problem could be a combination of both issues. Moving this card back to Ready since we have discussed and this issue is blocking the users from viewing reports daily that they usually do.

**Comment by mahalakshme** [comment]
@vinayvenu I felt whoever picks up this card can do the necessary analysis since fixing of issues also requires some analysis.

**Comment by ashusvnath** [comment]
The user who raised the issue claims that this is no longer an problem on the support ticket.
This is based on Nupoor's latest comment on https://avni.freshdesk.com/a/tickets/3050
