### ISSUE TITLE
Avni read db to medium and change in password for prod main

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-infra#17]
- running queries on read db is becoming very slow and this must also be impacting the customers queries from reports
- due to this I have been running queries on prod master which is not a good idea
- ~~the prod main password can be made confidential so that only few people have the password for it. this would force all database updates to go through a review process~~

**Comment by vinayvenu** [comment]
- Read db moved to medium
- prod main password change requires downtime for avni-server, avni-etl and avni-media. There are also other security issues that will need to be fixed to reduce the db login footprint. Moving it out of scope of this story

**Comment by vinayvenu** [comment]
Added https://github.com/avniproject/avni-security/issues/83 to handle the items moved out of scope.
