### ISSUE TITLE
Migrate Superset to Docker based setup

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-infra#19]
### Need:
Setup latest version of superset to use Docker Container based setup for easy upgrades.

### Acceptance criteria:
- Setup Container based superset of version 4.1 using prerelease rds superset DB
- Configure it similar to prod superset
- After User Acceptance Test successful confirmation, switch the superset dockerized system to use prod rds and route all superset routing traffic to the new one
- Bring down all other migration infra after taking necessary backup

## Tech Steps (Blue Green Deployment approach)
1. Take snapshot of superset ec2 instance EBS volume
2. Setup a new EC2 instance superset Blue 
    - use Docker container setup to install version 4.1 superset
3. Configure new superset to work with Pre-release RDS superset DB
4. Configure new superset to have all required features enabled (Tagging, Drill down, etc..)
5. Configure SSL certificate using nginx for the superset
6. Validate that all reports are working in new superset same as the old one
If all things are working fine and Implementation team gives go ahead, then 
7. Stop both old and new Superset services
8. Point new superset to Prod RDS superset db 
9. Switch superset Hostname from old to the new superset ec2 instance
10. Take one last backup of old superset and bring it down
11. Remove the new superset Route53 entry

### suggestions: Ignore
- current version
- prod ready not in scope.
- one-click installer/ via docker /ansible
- upgrade current machine to 4.1 - since already tried in security env

**Comment by vedfordev** [comment]
move card to qa ready. implementation team will do sanity test. @himeshr @pkundu
