### ISSUE TITLE
RDS CA certificates expiring

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-infra#22]
![Image](https://github.com/avniproject/avni-infra/assets/10369963/fc3af9c0-810f-4467-8567-4a334b1a2b4d)

```[tasklist]
### Tasks
```
* The affected RDS instances are below
                  proddb02, proddb02-read, superset-db.  - all are having "rds-ca-2019" as their Certificate Authority which is getting expired on August 22, 2024 and we need to update the Certificate Authority to make the DB healthy and security is upto date.

* The changes we need to make is Modify the Certificate Authority to "rds-ca-rsa2048-g1(default)" which expires on May 20, 2061.

Suggestion:
- Apply in following order:- superset-db, proddb02-read, proddb02

**Comment by Balamuruganjeevi** [comment]
* The affected RDS instances are below
                  proddb02, proddb02-read, superset-db.  - all are having "rds-ca-2019" as their Certificate Authority which is getting expired on August 22, 2024 and we need to update the Certificate Authority to make the DB healthy and security is upto date.

* The changes we need to make is Modify the Certificate Authority to "rds-ca-rsa2048-g1(default)" which expires on May 20, 2061.

**Comment by 1t5j0y** [comment]
@Balamuruganjeevi please check stagingdb as well. Apply changes to it before prod-read and prod
