### ISSUE TITLE
Add alert for performance metrics

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-infra#23]
### Issue:
- Add notification to product team via email related to performance metrics. 

### Acceptance criteria:
- The below points are for RWB env
- Add notification for the metric: ```Avg response time``` from newrelic - we already have this for Avni. Looks like currently the notification is linked to only vinay's mail id. Try to make it to send notification to product team.
- notification when diskspace for all machines in AWS reaches, say 80% 
- also make sure notification setup via freshping when RWB server is down

**Comment by mahalakshme** [comment]
@vinayvenu should we add newrelic alarm to identify when response time degrades? I felt the above ll suffice, Wondered, if there are too many alerts we might not monitor anything.

**Comment by mahalakshme** [comment]
Vinays comment in skype: newrelic alerts might be better since they measure the true problem, irrespective of what is happening on the infra side

so @vinayvenu since not all performance degradation/overload issues in AWS can be correspondingly identified from some newrelic indicator(correct me if I am wrong), have modified the AC accordingly.

**Comment by vinayvenu** [comment]
We are talking alerts, not analysis. 

For alerts, newrelic is enough.

**Comment by 1t5j0y** [comment]
RWB Newrelic account:
- Added Average Response Time across 5 mins > 1 sec alert
- Added Storage alert > 80% for prod servers
Will monitor how much data is additionally sent for infra monitoring and add alerting for reporting and non prod environment as well if we are not in danger of breaching the free plan limits.

Avni Newrelic account
- Updated existing alert condition to also notify cron-alerts
