### ISSUE TITLE
Services running using pm2 do not restart on server reboot

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-infra#31]
rules-server, avni-media are run using pm2. If the instance on which these are running gets restarted, these services need to be configured to be restarted too.

Impacted sevices:
- Media-server (Integration instance)
- Rules-server (Avni-server instance)

Environments:
- Prod
- Prerelease
- Staging
- RWB_prod
- RWB_Staging

**Comment by himeshr** [comment]
Refer to https://stackoverflow.com/questions/60095316/does-pm2-auto-restart-application-after-reboot-by-default on how to do this.

**Comment by Balamuruganjeevi** [comment]
I have checked the scripts for both avni-media and rules-server both are looking fine have all steps included init. @1t5j0y can you please review.

**Comment by 1t5j0y** [comment]
@Balamuruganjeevi have you modified any code which needs to be reviewed?
cc: @himeshr

**Comment by Balamuruganjeevi** [comment]
No nothing have changed and i have modified something yesterday but it won't work so i replaced it, so nothing changed.

**Comment by 1t5j0y** [comment]
@Balamuruganjeevi since we have confirmed that the issue is present (atleast in avni-media) yesterday (simulated by rebooting prerelease integration server) and no change has been made, the issue won't be fixed and there is nothing to review.
Moving this back to 'Ready' so someone else can take a look.

**Comment by 1t5j0y** [comment]
avni-media had this issue because the command output by running pm2 startup (which creates the service to resurrect pm2 processes) was not being run.
rules-server is getting restarted on server reboot as the avni-infra scripts already include this step.

**Comment by 1t5j0y** [comment]
Tested on staging and prerelease by rebooting server and ensuring avni-media came back online as part of fix dev.
