### ISSUE TITLE
Setup reserved instances for EC2 and RDS

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-infra#4]
We are still paying on-demand prices for AWS resources though we have always-on systems.

Reserved instances give 20-30% savings. There are options to make zero upfront payment for 1 year which are convertible to other resource classes and can give us quick easy savings. Resources across the same resource class type can share any reservations we setup i.e. if we setup a t3.medium RI, it will get applied to any t3 resource we have.. it doesn't necessarily tie to a t3.medium resource.

**Comment by himeshr** [comment]
We have done this as an activity last week for Avni Account.
