### ISSUE TITLE
Add superset in Reporting Configuration

### ISSUE THREAD

**Issue by vedfordev** [avniproject/avni-infra#43]
**Context :** If you go to login page of Avni. currently it shows only two reporting tool Metabase and jasper. Superset is not visible.  

**Tasks :** 
- [ ] create List of reporting tool and if it is missing in server configuration then add it 

[Reference](https://github.com/avniproject/avni-infra/blob/3c79a629cd71da03d3fc272b8d481b77df790e42/configure/group_vars/prod_vars.yml#L80)

**Comment by 1t5j0y** [comment]
Pushed to master so this will reflect with next deployment to each environment.

**Comment by dinesh2096** [comment]
QA Reference : 

[Click here to watch the video](https://drive.google.com/file/d/1_HfWobQ1_51JiXdTixZrCtK_piPAo3c7/view?usp=drive_link)
