### ISSUE TITLE
Do away with Keycloak and Minio in Staging environment

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-infra#54]
## Need
Currently staging environment is configured to work in IDPType = 'Both' implying that it can have an Org setup to work with either cognito or keycloak. This results in the need to keep Staging Keycloak and minio systems up and running all time, though they do not get used.

## AC
Only in Staging environment
- Switch IDPType to 'Cognito'  
- Disable Keycloak
- Disable Minio
- Bring down Keycloak and Minio EC2 instances

**Comment by petmongrels** [comment]
Lets see if we can have avni-server start without keycloak and cognito running. More likely there is an option to do this in upgraded version of spring if not in the current one.

**Comment by himeshr** [comment]
> Lets see if we can have avni-server start without keycloak and cognito running. More likely there is an option to do this in upgraded version of spring if not in the current one.

You meant Keycloak and Minio.? 
We can currently change the settings to just run with Cognito, you do not wanna do that.? And instead just get it to ignore keycloak / minio connection issues and start-up?

**Comment by petmongrels** [comment]
- Yes. keycloak and minio
- For now we can change the config to cognito, if that allows us to stop these two services immediately
- We can test that server starts without them running as final activity and change config to both and keep it in that mode. We can also test that if keycloak and minio is started then we have no issues.

**Comment by himeshr** [comment]
- Running with idpType=Both, with the Keycloak instance stopped, caused problem during server startup.
- Starting the Keycloak and Minio stopped instances and enabling their usage in config (staging_vars => avni_server_idp_type: "cognito") works as expected, but would need following additional activity
- - Update IP address in Route53 for "minio-staging.avniproject.org" and "keycloak-staging.avniproject.org" as per new ip allocated to their instances
- - Renew SSL certs for the 2 machines(minio and Keycloak) using let's encrypt commands if needed
