### ISSUE TITLE
Migrate RDS T2 instances

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-infra#9]
RDS T2 instances will be EOL in April 2024.
reportingdb is still on t2 and needs to changed to a new instance type.

**Comment by Balamuruganjeevi** [comment]
@himeshr and @1t5j0y there is no T2 RDS instances are running in both the ENV and the card is still Open, Someone have take a look and let me know we can close the card or not.

**Comment by himeshr** [comment]
Yes, no action required on this card.
